### ISSUE TITLE
Module wont roll tables from compendiums that are linked onto journals

### ISSUE THREAD

**Issue by ABrandau** [saif-ellafi/foundryvtt-rolltable-from-sidebar#2]
Not sure if the description is clear.

Basically if I link a table that is present in the world to a journal and right click on it, it rolls.
But if I link a table that is from a compendium that belongs to a module, i get this error.

![image](https://user-images.githubusercontent.com/11763228/195856178-814578d4-dcb8-416f-bcf4-8f5924063677.png)

**Comment by saif-ellafi** [comment]
Thank you for reporting this @ABrandau, sorry it took so long.
Fixed in https://github.com/saif-ellafi/foundryvtt-rolltable-from-sidebar/releases/tag/1.3.1
Best
