### ISSUE TITLE
Bug: right click on journal rolltable doesnt work

### ISSUE THREAD

**Issue by roi007leaf** [saif-ellafi/foundryvtt-rolltable-from-sidebar#4]
Currently on PF2E latest version, right clicking a rolltable link in a journal doesnt do anything, latest foundry and module version

**Comment by roi007leaf** [comment]
adding to the bug:
Copying rolltable or duplicating a rolltable is also broken with the module active, it copies it with empty entries

**Comment by MaineKnight** [comment]
DND 5e. It works from the roll table tab, but roll tables in compendiums it shows the "dice" but left click does nothing

**Comment by Wotn9** [comment]
For PF2E : That's quite f*cked up but actually it does not bug if the Default journal sheet is set to Default Text Editor.  if you change it to TinyMCE for example, RFS stop working properly.

**Comment by guldelox** [comment]
Still happening when right-clicking from a journal. Throws this error: 
![image](https://github.com/saif-ellafi/foundryvtt-rolltable-from-sidebar/assets/67302749/9e039292-f04f-4d3e-b128-dff9dd0ca80b)

**Comment by SerotoninRonin** [comment]
Still happening with Twilight:2000.
